import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Naver from "@/components/Naver/Naver";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Rynix-Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="h-32 mb-2">
      <Naver/>
      </div>
       <div className="max-w-screen-xl mx-auto">
       {children}
       </div>
      </body>
    </html>
  );
}
